import test from 'node:test';
import assert from 'node:assert/strict';
import handler from './api/intake.js';
function res(){return {code:200,status(n){this.code=n;return this},json(value){this.body=value;return this},setHeader(){}};}
const request={method:'POST',headers:{host:'www.nachoslegacy.com',origin:'https://www.nachoslegacy.com','x-forwarded-for':'test'},body:{submissionId:'00000000-0000-4000-8000-000000000001',name:'Test',phone:'+14845550111',vehicle:{raw:'Honda'}}};
test('website does not report successful submission without CRM configuration',async()=>{delete process.env.CRM_INTAKE_URL;delete process.env.INTAKE_SHARED_SECRET;const r=res();await handler(request,r);assert.equal(r.code,503);assert.equal(r.body.ok,undefined);});
test('website forwards full inquiry with secret only on server and returns saved case',async()=>{process.env.CRM_INTAKE_URL='https://crm.example.com/api/intake/nachos';process.env.INTAKE_SHARED_SECRET='test-secret';const original=globalThis.fetch;let forwarded;globalThis.fetch=async(url,options)=>{forwarded=options;return {ok:true,status:201,json:async()=>({caseId:'saved',caseNumber:'NL-TEST'})}};const r=res();await handler(request,r);assert.equal(r.code,201);assert.equal(r.body.caseId,'saved');assert.equal(forwarded.headers['x-intake-secret'],'test-secret');assert.deepEqual(JSON.parse(forwarded.body),request.body);globalThis.fetch=original;delete process.env.CRM_INTAKE_URL;delete process.env.INTAKE_SHARED_SECRET;});
test('cross origin submissions are rejected',async()=>{const r=res();await handler({...request,headers:{...request.headers,origin:'https://other.example.com'}},r);assert.equal(r.code,403);});
test('upstream failure leaves inquiry unconfirmed rather than inventing success',async()=>{process.env.CRM_INTAKE_URL='https://crm.example.com/api/intake/nachos';process.env.INTAKE_SHARED_SECRET='test-secret';const original=globalThis.fetch;globalThis.fetch=async()=>({ok:false,status:503,json:async()=>({error:'database error'})});const r=res();await handler(request,r);assert.equal(r.code,503);assert.equal(r.body.ok,undefined);globalThis.fetch=original;delete process.env.CRM_INTAKE_URL;delete process.env.INTAKE_SHARED_SECRET;});
