import {readFile,writeFile,mkdir,rm,cp} from 'node:fs/promises';
import path from 'node:path';
const site=JSON.parse(await readFile('src/data/site.json','utf8'));
const services=JSON.parse(await readFile('src/data/services.json','utf8'));
const origin=new URL(site.url).origin;
const esc=value=>String(value).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const fragment=(lang,kind,name)=>readFile(`src/${kind}/${lang}/${name}.html`,'utf8');
const route=(lang,slug='')=>(lang==='es'?'/es/':'/')+(slug?slug+'/':'');
const slugs={collision:'collision-repair',frame:'frame-repair',refinishing:'auto-refinishing',insurance:'insurance-claim-support',body:'dent-body-repair',paint:'paint-color-matching'};
const copy={en:{home:'Home',services:'Services',includes:'What this service includes',next:'Start with a vehicle assessment',nextText:'Call or send your vehicle year, make, model and a short description of the damage. An in-person inspection is needed to determine the repair scope, price and timing.',assessment:'Request an assessment ↗',related:'Related services',local:'Local collision repair · Lansdowne, PA',view:'View all services →'},es:{home:'Inicio',services:'Servicios',includes:'Qué incluye este servicio',next:'Comenzá con una evaluación del vehículo',nextText:'Llamá o enviá año, marca, modelo y una breve descripción del daño. Es necesario inspeccionar el vehículo para determinar el alcance, el precio y el plazo de reparación.',assessment:'Solicitar evaluación ↗',related:'Servicios relacionados',local:'Reparación de colisiones · Lansdowne, PA',view:'Ver todos los servicios →'}};
const business={'@type':'AutoBodyShop','@id':origin+'/#business',name:site.name,url:origin+'/',telephone:site.phone,email:site.email,image:site.image,logo:site.logo,address:{'@type':'PostalAddress',streetAddress:site.address.street,addressLocality:site.address.city,addressRegion:site.address.region,postalCode:site.address.postal,addressCountry:'US'},openingHoursSpecification:[{'@type':'OpeningHoursSpecification',dayOfWeek:['Monday','Tuesday','Wednesday','Thursday','Friday'],opens:'09:00',closes:'18:00'}],sameAs:[site.instagram,site.maps],areaServed:site.serviceAreas.map(name=>({'@type':'City',name,addressRegion:'PA',addressCountry:'US'})),hasMap:site.maps,knowsLanguage:['English','Spanish'],knowsAbout:['Collision repair','Auto body repair','Structural repair','Automotive refinishing','Paint color matching','Vehicle restoration','Custom automotive paint','Professional detailing','Insurance claim support'],contactPoint:{'@type':'ContactPoint',telephone:site.phone,contactType:'customer service',availableLanguage:['English','Spanish']},additionalProperty:[{'@type':'PropertyValue',name:'Estimates',value:'Free by appointment; same-day urgent scheduling may be available'},{'@type':'PropertyValue',name:'Limited workmanship warranty',value:'One year; terms and exclusions apply'},{'@type':'PropertyValue',name:'Towing coordination',value:'Available; variable cost based on distance and transport complexity'}],hasOfferCatalog:{'@type':'OfferCatalog',name:'Collision and auto body repair services',itemListElement:Object.keys(slugs).map(key=>({'@type':'Offer',itemOffered:{'@type':'Service',name:services[key].en.title,url:origin+route('en','services/'+slugs[key])}}))}};
const faqData={en:[['How long will it take to repair my vehicle?','Timing varies by damage, insurance approval and parts availability. After approval, replacement parts generally arrive within 3 to 7 business days and repairable or refinishable parts typically require 3 to 4 days. Timing is not guaranteed.'],['Do you work with insurance companies?',`The shop regularly handles claims involving ${site.insurers.join(', ')} and can work with other insurers. This does not imply affiliation or endorsement. Coverage and approval depend on the policy and insurer.`],['Is there a warranty on the repair?','A one-year limited workmanship warranty is available for qualifying issues including paint die-back, peeling paint or clear coat, or an installed part becoming loose without later collision or external damage. Terms and exclusions should be confirmed in writing on the repair order.'],['Are estimates free, and do I need an appointment?','Estimates are free and normally require an appointment. Photos can support an initial assessment, but an in-person inspection is needed for a more accurate estimate. Same-day urgent scheduling may be available.'],['Can you arrange towing?','The shop can coordinate towing. Cost varies by distance and transport complexity. Insurance coverage for towing or rental vehicles depends on the policy.']],es:[['¿Cuánto tiempo tomará reparar mi vehículo?','El plazo varía según el daño, la aprobación del seguro y la disponibilidad de repuestos. Después de la aprobación, los repuestos suelen llegar en 3 a 7 días hábiles y las piezas reparables normalmente requieren de 3 a 4 días. Los plazos no están garantizados.'],['¿Trabajan con compañías de seguros?',`El taller atiende habitualmente reclamos de ${site.insurers.join(', ')} y puede trabajar con otras aseguradoras. Esto no implica afiliación ni recomendación. La cobertura y aprobación dependen de la póliza y la aseguradora.`],['¿La reparación tiene garantía?','Hay una garantía limitada de un año para casos elegibles, como opacidad de pintura, desprendimiento de pintura o clear coat, o una pieza instalada que se suelte sin un choque posterior ni daño externo. Las condiciones y exclusiones deben confirmarse por escrito en la orden.'],['¿Los estimados son gratuitos y necesito cita?','Los estimados son gratuitos y normalmente requieren cita. Las fotos sirven para una evaluación inicial, pero la inspección presencial es necesaria para un estimado más preciso. Puede haber disponibilidad el mismo día para urgencias.'],['¿Pueden coordinar una grúa?','El taller puede coordinar una grúa. El costo depende de la distancia y la complejidad del traslado. La cobertura de grúa o auto de reemplazo depende de la póliza.']]};
const mainPages=[
 {slug:'',title:{en:'Collision Repair & Auto Body Shop in Lansdowne, PA',es:'Taller de carrocería y colisiones en Lansdowne, PA'},description:{en:'Collision repair, frame repair and automotive refinishing at Nacho’s Legacy Body Shop in Lansdowne, PA. Family-owned, bilingual team. Call (484) 362-5873.',es:'Reparación de colisiones, chasis y pintura en Nacho’s Legacy Body Shop, Lansdowne, PA. Equipo familiar bilingüe. Llamá al (484) 362-5873.'},sections:['top','ticker','deductible','services','why','work','process','local-seo','faq','contact']},
 {slug:'services',title:{en:'Auto Body & Collision Repair Services in Lansdowne, PA',es:'Servicios de carrocería y colisiones en Lansdowne, PA'},description:{en:'Collision repair, frame work, body repair, complete or partial paint, restoration, custom paint and detailing in Lansdowne, PA.',es:'Colisiones, chasis, chapa, pintura completa o parcial, restauración, pintura personalizada y detailing en Lansdowne, PA.'},sections:['services','capabilities']},
 {slug:'about',title:{en:'About Nacho’s Legacy Body Shop in Lansdowne, PA',es:'Sobre Nacho’s Legacy Body Shop en Lansdowne, PA'},description:{en:'Meet Ignacio and Daniel Diaz and the family-owned Nacho’s Legacy team. 15 years of collision repair experience and personal attention in English and Spanish.',es:'Conocé a Ignacio y Daniel Diaz y al equipo familiar de Nacho’s Legacy: 15 años de experiencia en colisiones y atención en inglés y español.'},sections:['why','local-seo']},
 {slug:'repair-process',title:{en:'Our Collision Repair Process | Lansdowne, PA',es:'Nuestro proceso de reparación de colisiones | Lansdowne, PA'},description:{en:'Understand each step at Nacho’s Legacy: first contact, damage inspection, body and paint repair, and final review before vehicle delivery.',es:'Conocé cada etapa en Nacho’s Legacy: contacto inicial, inspección de daños, reparación de carrocería y pintura, y revisión antes de la entrega.'},sections:['accident','process']},
 {slug:'our-work',title:{en:'Collision & Body Repair Gallery in Lansdowne, PA',es:'Galería de reparaciones de carrocería en Lansdowne, PA'},description:{en:'See collision repair, body work and automotive refinishing photos from the Nacho’s Legacy team in Lansdowne, PA. Contact the shop about your vehicle.',es:'Mirá fotos de colisiones, trabajos de carrocería y pintura del equipo de Nacho’s Legacy en Lansdowne, PA. Consultanos por tu vehículo.'},sections:['work']},
 {slug:'faq',title:{en:'Collision Repair & Insurance Questions in Lansdowne, PA',es:'Preguntas sobre colisiones y seguros en Lansdowne, PA'},description:{en:'Answers about repair timing, insurance claims, deductibles, assessments and structural repairs at Nacho’s Legacy Body Shop in Lansdowne, PA.',es:'Respuestas sobre plazos, seguros, deducibles, evaluaciones y reparación estructural en Nacho’s Legacy Body Shop, Lansdowne, PA.'},sections:['faq']},
 {slug:'contact',title:{en:'Contact & Directions | Body Shop in Lansdowne, PA',es:'Contacto y ubicación | Taller en Lansdowne, PA'},description:{en:'Visit Nacho’s Legacy at 27 Third Street, Lansdowne, PA 19050. Open Monday–Friday, 9 AM–6 PM. Call (484) 362-5873 or request a vehicle assessment.',es:'Visitá Nacho’s Legacy en 27 Third Street, Lansdowne, PA 19050. Lunes a viernes, 9 a 18 h. Llamá al (484) 362-5873 o solicitá una evaluación.'},sections:['contact','accident']},
 {slug:'service-areas',title:{en:'Collision Repair Service Areas near Lansdowne, PA',es:'Áreas de servicio de reparación cerca de Lansdowne, PA'},description:{en:'Body and collision repair for drivers in Lansdowne, Darby, Upper Darby, Folcroft, Clifton Heights, Yeadon and Drexel Hill, Pennsylvania.',es:'Reparación de carrocería y colisiones para Lansdowne, Darby, Upper Darby, Folcroft, Clifton Heights, Yeadon y Drexel Hill, Pennsylvania.'},sections:['areas','contact']}
];
const pages=[...mainPages,...Object.entries(slugs).map(([key,slug])=>({slug:'services/'+slug,key,title:Object.fromEntries(['en','es'].map(lang=>[lang,services[key][lang].title+' '+(lang==='es'?'en':'in')+' Lansdowne, PA'])),description:Object.fromEntries(['en','es'].map(lang=>[lang,services[key][lang].text])),sections:[]}))];
await rm('dist',{recursive:true,force:true});await mkdir('dist',{recursive:true});await cp('public','dist',{recursive:true});
const manifest=[];
for(const lang of ['en','es']){
 const c=copy[lang];
 for(const page of pages){
  const url=origin+route(lang,page.slug),alternate=route(lang==='en'?'es':'en',page.slug);
  let content='';for(const section of page.sections)content+=await fragment(lang,'sections',section);
  if(page.key){const service=services[page.key][lang];const image=site.serviceImages[page.key];content=`<section class="service-detail"><div><h2>${c.includes}</h2><p>${esc(service.text)}</p><ul>${service.list.map(item=>`<li>${esc(item)}</li>`).join('')}</ul><h2>${c.next}</h2><p>${c.nextText}</p><button class="btn primary open-estimate" type="button">${c.assessment}</button></div><img src="${esc(image)}" alt="${esc(service.title)} — Nacho's Legacy Body Shop" width="900" height="700" loading="lazy"></section>`;
   if(page.key==='insurance')content+=await fragment(lang,'sections','deductible');
   content+=`<section class="section"><p class="eyebrow">${c.related}</p><div class="footer-links">${Object.keys(slugs).filter(key=>key!==page.key).map(key=>`<a class="section-link" href="${route(lang,'services/'+slugs[key])}">${esc(services[key][lang].title)} →</a>`).join('')}</div></section>`;
  }
  const intro=page.slug?`<section class="page-intro"><nav class="breadcrumbs" aria-label="${lang==='es'?'Ruta de navegación':'Breadcrumb'}"><a href="${route(lang)}">${c.home}</a>${page.key?` / <a href="${route(lang,'services')}">${c.services}</a>`:''} / <span>${esc(page.title[lang])}</span></nav><p class="eyebrow">${c.local}</p><h1>${esc(page.title[lang])}</h1><p>${esc(page.description[lang])}</p></section>`:'';
  let header=await fragment(lang,'partials','header');header=header.replaceAll('{{alternate}}',alternate).replaceAll('{{alternateLabel}}',lang==='en'?'Ver esta página en español':'View this page in English').replaceAll('{{languageLabel}}',lang==='en'?'EN / ES':'ES / EN');header=header.replace(`href="${route(lang,page.slug)}"`,`aria-current="page" href="${route(lang,page.slug)}"`);
  const graph=[business,{'@type':'WebSite','@id':origin+'/#website',url:origin+'/',name:site.name,inLanguage:['en-US','es-US']},{'@type':page.slug==='about'?'AboutPage':page.slug==='contact'?'ContactPage':'WebPage','@id':url+'#webpage',url,name:page.title[lang],description:page.description[lang],inLanguage:lang==='en'?'en-US':'es-US',isPartOf:{'@id':origin+'/#website'},about:{'@id':origin+'/#business'}}];
  if(page.slug){const items=[{name:c.home,item:origin+route(lang)}];if(page.key)items.push({name:c.services,item:origin+route(lang,'services')});items.push({name:page.title[lang],item:url});graph.push({'@type':'BreadcrumbList',itemListElement:items.map((item,i)=>({'@type':'ListItem',position:i+1,...item}))})}
  if(page.key)graph.push({'@type':'Service',name:services[page.key][lang].title,description:services[page.key][lang].text,url,provider:{'@id':origin+'/#business'},areaServed:site.serviceAreas.map(name=>({'@type':'City',name}))});
  if(page.slug==='faq')graph.push({'@type':'FAQPage',mainEntity:faqData[lang].map(([name,text])=>({'@type':'Question',name,acceptedAnswer:{'@type':'Answer',text}}))});
  const json=JSON.stringify({'@context':'https://schema.org','@graph':graph}).replace(/</g,'\\u003c');
  const html=`<!doctype html>\n<html lang="${lang}"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(page.title[lang])} | Nacho’s Legacy</title><meta name="description" content="${esc(page.description[lang])}"><meta name="robots" content="index,follow,max-image-preview:large"><link rel="canonical" href="${url}"><link rel="alternate" hreflang="en-US" href="${origin+route('en',page.slug)}"><link rel="alternate" hreflang="es-US" href="${origin+route('es',page.slug)}"><link rel="alternate" hreflang="x-default" href="${origin+route('en',page.slug)}"><meta property="og:type" content="website"><meta property="og:site_name" content="${esc(site.name)}"><meta property="og:title" content="${esc(page.title[lang])}"><meta property="og:description" content="${esc(page.description[lang])}"><meta property="og:url" content="${url}"><meta property="og:image" content="${esc(site.socialImage||site.image)}"><meta property="og:image:width" content="1200"><meta property="og:image:height" content="1200"><meta property="og:image:type" content="image/jpeg"><meta property="og:image:alt" content="Nacho’s Legacy Body Shop — complete logo"><meta property="og:locale" content="${lang==='en'?'en_US':'es_US'}"><meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="${esc(page.title[lang])}"><meta name="twitter:description" content="${esc(page.description[lang])}"><meta name="twitter:image" content="${esc(site.socialImage||site.image)}"><meta name="twitter:image:alt" content="Nacho’s Legacy Body Shop — complete logo"><link rel="icon" href="${esc(site.logo)}"><link rel="preconnect" href="https://res.cloudinary.com"><link rel="stylesheet" href="/assets/site.css"><script type="application/ld+json">${json}</script><script src="/assets/site.js" defer></script></head><body class="${page.slug?'inner-page':'home-page'}"><a class="skip-link" href="#main">${lang==='es'?'Ir al contenido':'Skip to content'}</a>${header}<main id="main">${intro}${content}${page.slug?`<section class="page-cta section"><p class="eyebrow">${c.local}</p><h2>${c.next}</h2><p>${c.nextText}</p><div class="buttons"><button type="button" class="btn primary open-estimate">${c.assessment}</button><a class="btn primary" href="tel:${site.phone}">(484) 362-5873</a></div></section>`:''}</main>${await fragment(lang,'partials','footer')}${await fragment(lang,'partials','widgets')}</body></html>`;
  const target=path.join('dist',route(lang,page.slug),'index.html');await mkdir(path.dirname(target),{recursive:true});await writeFile(target,html);manifest.push({url,path:target,lang,slug:page.slug});
 }
}
await writeFile('dist/sitemap.xml',`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml">${manifest.map(page=>`<url><loc>${page.url}</loc><xhtml:link rel="alternate" hreflang="en-US" href="${origin+route('en',page.slug)}"/><xhtml:link rel="alternate" hreflang="es-US" href="${origin+route('es',page.slug)}"/><xhtml:link rel="alternate" hreflang="x-default" href="${origin+route('en',page.slug)}"/></url>`).join('')}</urlset>`);
await writeFile('dist/robots.txt',`User-agent: *\nAllow: /\nDisallow: /api/\nSitemap: ${origin}/sitemap.xml\n`);
await writeFile('dist/404.html',`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex"><title>Page not found | Nacho’s Legacy</title><link rel="stylesheet" href="/assets/site.css"></head><body><main class="page-intro"><p class="eyebrow">404</p><h1>Page not found</h1><p>The page you requested is unavailable.</p><a class="btn primary" href="/">Back to home</a></main></body></html>`);
await writeFile('dist/llms.txt',`# ${site.name}\n\n> Family-owned collision and auto body repair center in Lansdowne, Pennsylvania. Service in English and Spanish.\n\n## Verified business information\n- Address: 27 Third Street, Lansdowne, PA 19050\n- Phone: (484) 362-5873\n- Email: ${site.email}\n- Hours: Monday–Friday, 9 AM–6 PM\n- Service areas: ${site.serviceAreas.join(', ')}, Pennsylvania\n- Services: collision repair, body and panel repair, structural/frame repair, complete or partial paint, color matching, restoration, custom paint, detailing and insurance-claim support\n- Free estimates normally require an appointment; photos can support an initial review, but an in-person inspection is required for accuracy\n- One-year limited workmanship warranty is available; conditions and exclusions apply and should be confirmed on the repair order\n- Towing can be coordinated at a variable cost based on distance and transport complexity\n- Repair timing, insurance coverage and deductible assistance are never guaranteed and must be confirmed for each case\n\n## English pages\n${manifest.filter(p=>p.lang==='en').map(p=>`- [${pages.find(x=>x.slug===p.slug).title.en}](${p.url})`).join('\n')}\n\n## Español\n- [Inicio](${origin}/es/)\n- [Áreas atendidas](${origin}/es/service-areas/)\n\nThis file is a factual reference for readers and tools. It does not guarantee indexing, ranking or AI citations.\n`);
await writeFile('dist/manifest.json',JSON.stringify(manifest,null,2));console.log(`Built ${manifest.length} static pages, sitemap, robots and shared assets.`);
